sonar.organization=kevinmoscoso
sonar.projectKey=KevinMoscoso_reservia

sonar.sources=reservia-backend/app,reservia-frontend/src
sonar.exclusions=**/node_modules/**,**/venv/**,**/migrations/**,**/__pycache__/**,**/*.test.jsx

sonar.python.coverage.reportPaths=reservia-backend/coverage.xml
sonar.javascript.lcov.reportPaths=reservia-frontend/coverage/lcov.info

sonar.python.version=3.12