DB_HOST = "localhost"
DB_PORT = 3306
DB_USER = "root"
DB_PASSWORD = "Admin123.."
DB_NAME = "reservia"
TEST_DB_NAME = "reservia_test"

SESSION_COOKIE_NAME = "reservia_session"
SESSION_COOKIE_SECURE = False
SESSION_INACTIVITY_TIMEOUT_MINUTES = 480

LOGIN_MAX_ATTEMPTS = 5

# Puede reducirse temporalmente durante pruebas manuales
LOGIN_LOCKOUT_MINUTES = 15

RESOURCE_SLOT_DURATION_MINUTES = 30
RESOURCE_OPERATING_START_TIME = "07:00"
RESOURCE_OPERATING_END_TIME = "21:00"